/**
 * Project library — 80+ projects extracted from the Elite Developer Project Ideas guide.
 * Each entry is resume/interview ready with architecture and deployment notes.
 */
(function (global) {
  function proj(o) {
    return Object.assign(
      { demo: "https://example.com/demo-placeholder", repo: "https://github.com/yourusername/project-placeholder", screenshot: "assets/screenshots/placeholder.svg" },
      o
    );
  }
  function p(cat, tier, emoji, title, desc, stack, diff, time, features, architecture, folderStructure, apis, database, deploy, securityNotes, scaleNotes, learn, resume, interview) {
    var colors = { frontend:"#1e3a8a", backend:"#065f46", fullstack:"#b8860b", devops:"#4c1d95", security:"#78350f", ai:"#0e7490", "data-ai":"#0e7490", blockchain:"#7c3aed" };
    return proj({
      id: cat + "-" + title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),
      cat: cat, tier: tier, emoji: emoji, color: colors[cat] || "#6366f1",
      title: title, desc: desc, stack: stack, diff: diff, time: time,
      features: features, architecture: architecture, folderStructure: folderStructure,
      apis: apis, database: database, deploy: deploy,
      securityNotes: securityNotes, scaleNotes: scaleNotes,
      learn: learn, resume: resume, interview: interview
    });
  }

  var projects = [
    // ===== FRONTEND =====
    p("frontend","beginner","✍️","DevBlog CMS with Live Preview","A markdown-based personal blog with real-time split-screen editing. Writers want instant markdown preview without switching tabs.",
      ["React","CodeMirror 6","marked.js","Prism.js"],"Easy","2-3 weeks",
      ["Split-screen editor","Syntax highlighting","Tag system","Dark/light mode","Export to HTML","Category filtering","Reading time estimator"],
      "Single-page React app with client-side routing. LocalStorage for persistence. CodeMirror for editing, marked.js for rendering.",
      "/src/components\n/src/hooks\n/src/utils\n/public",
      ["None (client-side only)"],"LocalStorage / IndexedDB","Vercel (static)",
      "Client-side only — no data leaves the browser. CSP headers on deploy.","Add PWA support, sync to GitHub Gist for cloud backup.",
      "React hooks, controlled inputs, CSS Grid/Flex, browser storage.","Live demo link; mention 2-3 week solo build.","Discuss offline-first architecture and localStorage limits."),

    p("frontend","beginner","🎯","Pomodoro Focus OS","A desktop-app-like focus timer with ambient sounds and productivity analytics. Developers need distraction-free focus tools.",
      ["Svelte","Web Audio API","CSS animations","Chart.js"],"Easy","2-3 weeks",
      ["Pomodoro timer","Ambient soundscapes","Task queue","Session history","Productivity heatmap","Custom themes","Browser notifications"],
      "Svelte single-page app with reactive state management. Web Audio API for sound generation. Chart.js for heatmap visualization.",
      "/src\n/src/components\n/src/stores\n/src/utils",
      ["Web Audio API","Notifications API"],"LocalStorage","Vercel / Netlify",
      "Minimal — all client-side. Notification permissions handled gracefully.","Add sync across devices, team workspaces, focus streak challenges.",
      "Svelte reactivity, Web APIs, animation, state management.","Show heatmap screenshot; mention sounds are procedurally generated.","Explain Svelte's reactive model vs React."),

    p("frontend","intermediate","🎨","Component Design System Studio","A Storybook-inspired interactive UI kit builder with live preview. Teams waste hours maintaining inconsistent component libraries.",
      ["React","CSS Variables","Monaco Editor","Radix UI","Tailwind"],"Medium","4-6 weeks",
      ["Design token editor","Live component preview iframe","Variant controls","Code export (JSX/Vue/Svelte)","Accessibility checker","Color palette generator","Typography scale tool"],
      "React app with iframe sandbox for live preview. Monaco Editor for token editing. CSS custom properties for theming. Radix UI primitives for accessible components.",
      "/apps/studio\n/apps/preview\n/packages/tokens\n/packages/components",
      ["Contrast ratio checker","Google Fonts API"],"PostgreSQL (saved design systems)","Vercel + Supabase",
      "GitHub OAuth. Iframe sandbox with restricted postMessage. CSP headers.","Add team collaboration, SSO, version history for design tokens.",
      "Design systems, iframe sandbox, CSS custom properties, AST basics.","Live demo + repo with sample component library.","Describe your design token architecture and iframe security model."),

    p("frontend","intermediate","🌍","WebGL Data Globe","An interactive 3D globe visualizing real-time global data. Flat maps fail to convey global scale and connections.",
      ["Three.js","Globe.gl","D3.js","React","WebGL shaders"],"Medium","5-7 weeks",
      ["3D globe with arc animations","Real-time flight/earthquake overlays","Click-to-zoom countries","Time-lapse data playback","Screenshot export"],
      "Three.js renderer with Globe.gl layer. React wrapper for UI overlays. Custom WebGL shaders for atmosphere and arc gradients.",
      "/src\n/src/globe\n/src/shaders\n/src/data\n/public",
      ["OpenSky Network (flights)","USGS (earthquakes)","CAIDA (internet maps)"],"None (live API data)","Vercel",
      "API keys on serverless functions. Rate limiting on external calls.","Add WebSocket for live updates, GPU instancing for performance.",
      "3D rendering, WebGL, data visualization, real-time APIs.","Most visually impressive project on your portfolio.","Discuss WebGL pipeline, shader programming, and 3D math."),

    p("frontend","intermediate","✨","CSS/GSAP Animation Playground","Live animation editor with timeline scrubbing and code export. No good interactive tool exists for learning web animations.",
      ["React","GSAP","Monaco Editor","Web Animations API"],"Medium","4-5 weeks",
      ["Monaco code editor","Live preview","Timeline scrubber","Easing curve editor","Preset library","Shareable URLs","CodePen/JSFiddle export"],
      "React app with GSAP-powered animation engine. Monaco Editor for code input. URL encoding for shareable animation states.",
      "/src\n/src/editor\n/src/preview\n/src/presets\n/src/utils",
      ["GSAP plugins","Lottie for JSON animations"],"Supabase (saved animations)","Vercel",
      "GitHub OAuth optional. URL encoding avoids server for basic sharing.","Add team workspaces, version history, AI animation generator.",
      "GSAP, animation principles, Monaco Editor API, URL state encoding.","Shareable URL links; preset library shows range.","Explain GSAP timeline vs CSS animations vs WAAPI tradeoffs."),

    p("frontend","advanced","🖌️","Browser-Based Figma Clone","A collaborative vector design tool with real-time multiplayer. Teams need self-hosted, privacy-first design collaboration.",
      ["React","HTML Canvas API","Yjs (CRDT)","WebSockets","Rough.js"],"Hard","12-16 weeks",
      ["Infinite canvas","Vector drawing tools","Real-time cursors","Component library","Frames/groups","Constraints","Export SVG/PNG/PDF","Version history","Comments","Component variants"],
      "CRDT-based op transforms via Yjs. Virtual viewport for canvas performance. WebWorkers for heavy computation. Canvas rendering with requestAnimationFrame.",
      "/packages/core\n/packages/canvas\n/packages/crdt\n/packages/ui\n/apps/web\n/apps/server",
      ["Yjs CRDT","WebRTC for P2P sync","y-websocket"],"PostgreSQL (documents), Redis (presence)","Railway (backend), Vercel (frontend), Cloudflare (WebSocket relay)",
      "Document-level permissions, signed URLs for exports. WebSocket authentication.","Horizontal WebSocket servers behind Redis pub/sub. Lazy-load pages.",
      "Canvas rendering, CRDT conflict resolution, virtual viewport, WebWorkers.","Crown jewel of frontend portfolio. Architecture diagram essential.","Explain CRDT vs OT, canvas rendering optimization, virtual viewport math."),

    p("frontend","advanced","📊","Frontend Performance Observatory","Lighthouse-style dashboard tracking Core Web Vitals over time. Teams have no visibility into performance regressions across deploys.",
      ["Next.js","Puppeteer","Lighthouse Node API","Chart.js","PostgreSQL"],"Hard","8-10 weeks",
      ["URL scanning","CWV tracking (LCP/FID/CLS/INP)","Bundle size analysis","Regression alerts","CI/CD webhook integration","Competitor benchmarking"],
      "Job queue for scan workers with BullMQ. Puppeteer running Lighthouse in headless Chrome. Time-series data in TimescaleDB.",
      "/apps/web\n/apps/worker\n/packages/scanner\n/packages/reporter\n/infra",
      ["Lighthouse API","Chrome DevTools Protocol","GitHub Actions webhook"],"TimescaleDB (metrics), PostgreSQL","Railway (Puppeteer workers), Vercel (dashboard)",
      "Sandboxed Puppeteer, SSRF protection on URL input.","Horizontal scan workers via BullMQ. Result caching in Redis.",
      "Headless browser automation, performance engineering, time-series data.","Show before/after perf improvements from your suggested fixes.","Discuss Lighthouse internals, Core Web Vitals, and performance budgets."),

    p("frontend","production-grade","🤖","AI-Powered Landing Page Builder","Describe your product — AI generates a full editable landing page. Non-developers can't build beautiful landing pages without designers.",
      ["Next.js 14","Claude API","Framer Motion","Tailwind CSS","tRPC","Prisma","PostgreSQL"],"Hard","16-20 weeks",
      ["AI page generation from prompt","Drag-drop section editor","Design tokens","Custom domain mapping","Analytics","A/B testing","SEO meta editor","One-click Vercel publish"],
      "Section schema as typed JSON. Streaming response for live preview. Versioned page snapshots. Custom domain CNAME mapping via Cloudflare.",
      "/apps/web\n/apps/api\n/packages/ai\n/packages/editor\n/packages/domains\n/infra",
      ["Claude API","Vercel Deploy API","Cloudflare DNS API","Stripe","Resend","Cloudinary"],"PostgreSQL (pages), S3 (assets), Redis (rate limits)","Vercel + Cloudflare Workers",
      "JWT auth, CSRF protection, CSP per published page, XSS sanitization.","Edge rendering via Vercel. Cloudflare for domain proxy. S3 for assets.",
      "Streaming AI, JSON schema for structured generation, edge functions.","Best startup idea. Show before/after of AI-generated page.","Design AI generation schema, streaming architecture, and domain routing."),

    p("frontend","production-grade","🧩","Universal Component Intelligence Layer","VS Code extension that analyzes React codebases and auto-generates docs. Large codebases have hundreds of undocumented components.",
      ["VS Code Extension API","Babel AST","Claude API","React","Storybook"],"Hard","14-18 weeks",
      ["Component dependency graph","Duplicate detection","Refactor suggestions","Storybook story generation","Usage heatmap","Dead code detector"],
      "Incremental AST parsing on file save. Code embeddings for similarity scoring. VS Code API for editor integration.",
      "/packages/parser\n/packages/analyzer\n/packages/ai\n/packages/view\n/extension",
      ["Babel parser","Claude API","GitHub API","Storybook API"],"SQLite (local), PostgreSQL (cloud)","VS Code Marketplace, Vercel (web)",
      "GitHub App OAuth. No code upload — all analysis is local by default.","AST-based incremental parsing. Similarity via code embeddings.",
      "AST parsing, VS Code API, code analysis algorithms, graph algorithms.","Open-source + premium cloud. Show duplicate detection UI.","Explain AST structure, code similarity algorithms, and VS Code extension lifecycle."),

    p("frontend","production-grade","🔧","Browser Extension Dev Tools Suite","A Postman + React DevTools hybrid as a browser extension. Developers switch between 5 tools for API testing, state inspection, and perf.",
      ["Chrome Extension MV3","React","TypeScript","Chrome DevTools Protocol"],"Hard","10-14 weeks",
      ["API request interceptor","Response inspector","React state tree","Network waterfall","localStorage editor","Cookie manager","CSS inspector"],
      "Chrome Extension MV3 architecture with service worker. DevTools panel API for inspector panel. chrome.debugger API for network interception.",
      "/src/panel\n/src/devtools\n/src/service-worker\n/src/content\n/packages/shared",
      ["Chrome DevTools Protocol","chrome.debugger API"],"IndexedDB (request history)","Chrome Web Store",
      "Chrome identity API. Limited permissions model with optional host access.","Add team sync, HAR export, performance budget audits.",
      "Browser extension architecture, Chrome DevTools Protocol, MV3.","High-visibility on Chrome Web Store drives downloads.","Discuss MV3 vs MV2, service worker lifecycle, and Chrome API security model."),

    // ===== BACKEND =====
    p("backend","beginner","🔗","URL Shortener with Analytics","Build bit.ly with click analytics, geo-data, and QR codes. Marketing teams need link tracking without paying for enterprise tools.",
      ["Node.js","Express","PostgreSQL","Redis","Chart.js"],"Easy","2-3 weeks",
      ["Custom slugs","Expiry dates","Click analytics (geo/device/referrer)","QR code generation","Dashboard charts","API key auth","Rate limiting"],
      "REST API with Express. PostgreSQL for links and clicks. Redis for caching and rate limiting. Nanoid for slug generation.",
      "/src/routes\n/src/middleware\n/src/db\n/src/utils\n/dashboard",
      ["ipapi.co (geo lookup)","QRCode.js","Nanoid"],"PostgreSQL (links/clicks), Redis (cache)","Railway / Render",
      "JWT auth. Rate limiting via Redis sliding window. Input sanitization on custom slugs.","Add sharded databases, CDN for QR codes, Redis Cluster.",
      "REST API design, Redis caching, DB indexing, IP geolocation.","Show dashboard with real click analytics and QR code demo.","Design database schema for high-write click tracking."),

    p("backend","beginner","💬","Real-Time Chat API","WhatsApp-style backend with rooms, DMs, and typing indicators. Most chat tutorials lack production features like read receipts.",
      ["Node.js","Socket.io","MongoDB","JWT","Cloudinary"],"Easy","3-4 weeks",
      ["WebSocket rooms","DMs","Read receipts","Typing indicators","File uploads","Message reactions","Message threading","Push notifications"],
      "Socket.io for real-time bidirectional communication. MongoDB for message persistence. JWT for authentication with refresh tokens.",
      "/src/socket\n/src/routes\n/src/models\n/src/middleware\n/src/workers",
      ["Socket.io","Firebase Cloud Messaging","Cloudinary"],"MongoDB (messages), Redis (presence)","Railway",
      "JWT with refresh rotation. Message-level encryption. File upload validation.","Add horizontal Socket.io scaling with Redis adapter. Message pagination.",
      "WebSockets, event-driven design, session management, file handling.","Show typing indicators and read receipts in action.","Explain WebSocket handshake, room management, and horizontal scaling with Redis."),

    p("backend","intermediate","⚡","Distributed Job Queue System","Build BullMQ from scratch — Redis-backed job queue with monitoring. Developers don't understand job queues deeply until they build one.",
      ["Node.js","Redis","Docker","React"],"Medium","5-7 weeks",
      ["Priority queues","Exponential backoff retries","Dead-letter queues","Cron-based scheduling","Worker concurrency control","Metrics dashboard","Job dependency chains","Webhook notifications"],
      "Redis Sorted Sets for priority queues. Lists for job streams. ioredis for Redis client. Prometheus for metrics.",
      "/src/queue\n/src/worker\n/src/scheduler\n/dashboard\n/pkg",
      ["ioredis","cron-parser","Prometheus"],"Redis (queue state), PostgreSQL (history)","Docker Compose on VPS",
      "API key for admin dashboard. Job payload encryption. Dead-letter alerts.","Add Redis Cluster for horizontal scaling. Job partitioning.",
      "Redis data structures, async patterns, worker pools, metrics.","Show dashboard with real job processing metrics.","Explain Redis data structures used for priority queues and rate limiting."),

    p("backend","intermediate","🔎","GraphQL API Gateway with Federation","Federate multiple REST microservices into a single GraphQL endpoint. Frontend teams fight over which service owns which data.",
      ["Apollo Server 4","DataLoader","Redis","JWT","TypeScript"],"Medium","6-8 weeks",
      ["Schema stitching","DataLoader batching","Response caching","Persisted queries","Field-level rate limiting","Query complexity analysis","Auto REST-to-GraphQL wrapping"],
      "Apollo Federation for subgraph composition. DataLoader for batching and caching. query complexity analysis for DoS protection.",
      "/gateway\n/subgraphs/users\n/subgraphs/orders\n/subgraphs/products\n/packages/shared",
      ["Apollo Federation","graphql-shield","Apollo Sandbox"],"PostgreSQL (subgraph data), Redis (cache)","Railway",
      "JWT with field-level permission rules. Query depth limiting.","Add federated tracing. Subgraph health checks and circuit breakers.",
      "GraphQL federation, N+1 problem, DataLoader, query planning.","Show schema stitching with two subgraphs. Architecture diagram.","Explain Apollo Federation vs schema stitching and the N+1 problem."),

    p("backend","intermediate","🛒","Event-Driven E-Commerce Backend","Microservices e-commerce with Kafka and Saga pattern. Distributed transactions in e-commerce are notoriously hard.",
      ["Go","Apache Kafka","PostgreSQL","Docker Compose","Stripe"],"Medium","8-12 weeks",
      ["Order service","Inventory service","Payment service","Notification service","Saga orchestration","Outbox pattern","Event replay","Dead-letter handling","Admin dashboard"],
      "Each service owns its DB, communicates via Kafka events. Saga handles compensating transactions on failure. Outbox pattern for reliable messages.",
      "/services/order\n/services/inventory\n/services/payment\n/services/notification\n/lib/kafka\n/infra",
      ["Stripe API","Kafka","Zookeeper","Prometheus"],"PostgreSQL per service (DB per service)","Docker Compose (dev), Kubernetes (prod)",
      "JWT (customer), API key (service-to-service). mTLS between services.","Kafka partitioning per order ID. Horizontal pod autoscaling.",
      "Saga pattern, outbox pattern, CQRS, event sourcing, Kafka.","Complex distributed system — shows senior-level architecture skills.","Walk through a complete order flow with Saga compensating transactions."),

    p("backend","advanced","⏱️","Time-Series Database Engine","Write a minimal InfluxDB-like TSDB in Go with LSM trees. Developers don't understand how time-series databases actually work.",
      ["Go","Custom storage engine"],"Hard","16-20 weeks",
      ["Write-ahead log (WAL)","LSM tree storage engine","Gorilla XOR compression","HTTP API (write/query)","SQL-like query language","Compaction strategy","Range query optimization","Retention policies"],
      "Memtable → WAL → SSTable flush → compaction. Delta encoding for float compression. Time-range index for fast queries.",
      "/engine/wal\n/engine/memtable\n/engine/sstable\n/engine/compaction\n/api\n/pkg",
      ["None (this IS the engine)"],"Custom LSM tree implementation","Binary + Docker",
      "Basic auth for HTTP API. TLS. No shell injection in query parser.","Horizontal sharding by time range. Replica sets.",
      "Systems programming, LSM trees, compression, concurrency in Go.","Impressive systems-level project. Publish benchmark vs InfluxDB.","Explain LSM tree structure, compaction strategies, and Gorilla compression."),

    p("backend","advanced","🚦","API Rate Limiter as a Service","Drop-in SDK + cloud service for flexible API rate limiting. Every API team reinvents rate limiting poorly.",
      ["Rust","Redis","gRPC","React"],"Medium","10-14 weeks",
      ["5 algorithms (token bucket, leaky bucket, fixed/sliding window)","Distributed coordination via Redis","Per-user/IP/endpoint limits","Admin dashboard","SDK for Node/Python/Go"],
      "Lua scripts ensure atomic Redis operations. Shadow mode for testing. gRPC for high-performance SDK communication.",
      "/core/engine\n/core/algorithms\n/sdks/node\n/sdks/python\n/sdks/go\n/dashboard\n/infra",
      ["Redis Lua scripts","Prometheus","Grafana"],"Redis (counters), PostgreSQL (config/billing)","Kubernetes, multi-region Redis",
      "API key hashing. TLS everywhere. No timing bypass vulnerabilities.","Redis Cluster. Regional edge nodes. Eventual consistency.",
      "Rate limiting algorithms, Lua scripting, Rust, distributed systems.","Show benchmark comparing all 5 algorithms.","Compare sliding window log vs token bucket vs leaky bucket tradeoffs."),

    p("backend","production-grade","🏗️","Developer API Platform (Kong Clone)","Full API management with gateway, portal, billing, and plugin system. SMBs need a simpler managed version of Kong.",
      ["Go","React","PostgreSQL","Redis","Stripe","Kubernetes"],"Hard","20-30 weeks",
      ["Reverse proxy gateway","Developer portal","Usage analytics","Stripe billing","Plugin marketplace (auth/cache/transform/rate-limit)","API versioning","OpenAPI import","Team management","Webhook delivery"],
      "Plugin chain pattern (middleware). Hot-reload config without restart. Shadow traffic for testing. Stateless gateway pods.",
      "/gateway\n/portal\n/admin\n/plugins\n/billing\n/analytics\n/infra",
      ["Stripe","SendGrid","GitHub OAuth","OpenAPI 3.0 parser"],"PostgreSQL (config), Redis (cache/rate limiting), ClickHouse (analytics)","Helm chart for self-hosted, managed cloud option",
      "mTLS, WAF rules, secret injection from Vault, RBAC.","Stateless gateway pods, config synced via Redis, horizontal scaling.",
      "Reverse proxy, plugin architecture, API gateway patterns, billing.","Enterprise-grade project. Shows full platform engineering skills.","Design plugin middleware chain, hot-reload config, and gateway scaling."),

    p("backend","production-grade","📨","Webhook Delivery Platform (Svix Clone)","Reliable webhook delivery with retries, signatures, and developer portal. Implementing reliable webhooks is surprisingly hard.",
      ["Go","PostgreSQL","Redis","React","BullMQ"],"Hard","12-16 weeks",
      ["Endpoint management","HMAC signing","Retry with exponential backoff","Dead-letter queue","Delivery logs","Local testing tunnel","SDK generation","Rate limiting per endpoint","Payload transformation"],
      "Fan-out per webhook event. Per-endpoint concurrency limits. Idempotency keys for duplicate prevention. Stripe-style signing.",
      "/api\n/worker\n/portal\n/sdks\n/tunnel\n/infra",
      ["ngrok-like tunnel","Stripe-style signing"],"PostgreSQL (deliveries/endpoints), Redis (queue)","Kubernetes",
      "API key per application. HMAC signature verification. Rate limiting.","Horizontal worker scaling via BullMQ. Regional queue sharding.",
      "Delivery guarantees, HMAC signing, queue design, at-least-once delivery.","Show retry logic with exponential backoff in action.","Explain at-least-once delivery, idempotency keys, and dead-letter queues."),

    p("backend","production-grade","⚙️","Distributed Config Management System","Consul + LaunchDarkly hybrid: feature flags + distributed config. Feature flags and config management are critical but expensive.",
      ["Go","etcd","gRPC","React","PostgreSQL"],"Hard","14-18 weeks",
      ["Key-value config store","Feature flags with % rollout","A/B targeting","Audit log","Real-time push (gRPC stream)","Multi-env support","Rollback","Approval workflows"],
      "etcd for distributed key-value storage with Raft consensus. gRPC streaming for real-time config push. RBAC with approval gates.",
      "/server\n/agent\n/cli\n/dashboard\n/sdks\n/infra",
      ["etcd","gRPC streaming","OpenTelemetry"],"etcd (distributed KV), PostgreSQL (audit)","Kubernetes operator pattern",
      "RBAC with approval gates. Signed config manifests. Audit trail.","etcd clustering for HA. Regional config replication.",
      "Distributed consensus (Raft), feature flag patterns, gRPC streaming.","Enterprise saleable project. Show A/B targeting and % rollout.","Explain Raft consensus, watch-based config propagation, and gRPC streaming."),

    // ===== FULL STACK =====
    p("fullstack","beginner","📊","Habit Tracker with Streaks + AI Coach","GitHub-contribution heatmap for your daily habits. Habit apps are either too complex or have no insight layer.",
      ["Next.js 14","Prisma","SQLite","Auth.js","Tailwind","Claude API"],"Easy","3-4 weeks",
      ["Habit creation","GitHub-style heatmap","Streak tracking","Weekly report email","Push reminders","Mobile PWA","Dark mode","Data export"],
      "Next.js App Router with server components. Prisma ORM for database. Auth.js for authentication. Cron jobs for weekly email.",
      "/app\n/src/components\n/src/lib\n/prisma\n/src/emails",
      ["Resend (emails)","web-push","Claude API"],"SQLite (dev), PostgreSQL (prod)","Vercel + Supabase",
      "Auth.js with Google OAuth. Row-level security on habits.","Add team challenges, habit streaks leaderboards, AI goal suggestions.",
      "Next.js App Router, Prisma ORM, PWA, scheduled jobs.","Show heatmap with streak tracking. AI coach sample output.","Explain PWA service worker caching and offline habit tracking."),

    p("fullstack","beginner","📄","Invoice Generator SaaS","Beautiful invoice creation with PDF export and payment tracking. Freelancers overpay for basic invoicing or use ugly spreadsheets.",
      ["Next.js","Prisma","PostgreSQL","Puppeteer","Stripe"],"Easy","3-5 weeks",
      ["Client management","Line items","Tax calculations","PDF generation","Payment status tracking","Recurring invoices","Email send","Currency support"],
      "Next.js with Prisma ORM. Puppeteer for server-side PDF generation. Stripe for payment processing. Resend for email delivery.",
      "/app\n/src/components\n/src/lib\n/prisma\n/src/emails",
      ["Puppeteer/Playwright (PDF)","Stripe","Resend"],"PostgreSQL","Vercel + Railway (Puppeteer)",
      "Auth.js authentication. Row-level security per user. PDF storage with signed URLs.","Add multi-currency, tax compliance reports, batch PDF generation.",
      "PDF generation, form handling, Stripe integration, email.","Show PDF output and Stripe payment flow.","Explain Puppeteer PDF generation, memory management, and fallback strategies."),

    p("fullstack","intermediate","🏢","Multi-Tenant SaaS Boilerplate","Production-ready SaaS starter — auth, billing, teams, admin panel. Every SaaS team rebuilds the same auth/billing/RBAC infrastructure.",
      ["Next.js 14","tRPC","Prisma","Stripe","Resend","Auth.js"],"Medium","8-12 weeks",
      ["Organization management","Role-based access (owner/admin/member)","Stripe subscriptions + usage metering","Email invitations","Audit logs","Admin super-panel","API key management","Onboarding flow"],
      "Multi-tenancy via organization scoping. Stripe subscription management with webhook handling. tRPC for end-to-end typesafe APIs.",
      "/apps/web\n/apps/api\n/packages/ui\n/packages/config\n/infra/terraform\n/.github",
      ["Stripe (billing)","Resend (email)","Sentry (errors)","PostHog (analytics)"],"PostgreSQL (Supabase)","Vercel + Supabase",
      "Auth.js with email magic link + Google OAuth. Row-level security by org.","Horizontal scaling per tenant. Read replicas for reporting.",
      "Multi-tenancy patterns, Stripe subscriptions, RBAC, SaaS architecture.","Best project for getting hired. Complete production system.","Design multi-tenant data model, Stripe subscription lifecycle, and RBAC matrix."),

    p("fullstack","intermediate","🖍️","Real-Time Collaborative Whiteboard","Miro-lite with sticky notes, drawing, shapes, and AI brainstorm mode. Remote teams need lightweight whiteboarding without Miro pricing.",
      ["Next.js","Liveblocks (CRDT)","HTML Canvas","Tailwind","Framer Motion","Claude API"],"Medium","8-10 weeks",
      ["Sticky notes","Freehand drawing","Shapes","Connectors","Text","Multiplayer presence (cursors/names)","Board sharing","PDF export","Template library"],
      "Liveblocks for CRDT-based real-time sync. HTML Canvas for drawing. Framer Motion for smooth animations. PDF export via jsPDF.",
      "/src/components\n/src/hooks\n/src/lib\n/public",
      ["Liveblocks","Claude API","jsPDF"],"Liveblocks (real-time), PostgreSQL (metadata)","Vercel",
      "Auth.js authentication. Board-level sharing permissions. File upload validation.","Add WebSocket fallback, offline support, infinite canvas.",
      "Canvas API, CRDT concepts, real-time collaboration, presence systems.","Show multiplayer cursors working in real-time.","Explain CRDT conflict resolution for concurrent shape editing."),

    p("fullstack","intermediate","📝","AI-Powered Resume Builder","Input experience — AI tailors resume to any job description in seconds. Tailoring resumes manually is tedious and most people do it poorly.",
      ["Next.js","tRPC","Prisma","Claude API","React-PDF","PostgreSQL"],"Medium","6-10 weeks",
      ["Resume builder (WYSIWYG)","Job description analyzer","AI tailoring","ATS score checker","Multiple templates","PDF export","Cover letter gen","Version history"],
      "Streaming AI responses for real-time tailoring. tRPC for typed API layer. React-PDF for server-side PDF generation.",
      "/src/app\n/src/components\n/src/lib\n/prisma\n/src/emails",
      ["Claude API (streaming)","react-pdf","Stripe"],"PostgreSQL","Vercel",
      "Auth.js authentication. Resume data encrypted at rest. PDF download security.","Add AI interview prep, skill gap analysis, recruiter marketplace.",
      "Streaming AI, PDF generation, document editing, structured output.","High conversion product — clear ROI for users.","Design structured output schema for AI-powered resume tailoring."),

    p("fullstack","advanced","📚","Notion-Style Knowledge OS","Block-based editor with databases, linked views, and AI page summaries. Notion is locked, expensive, and slow to add features.",
      ["Next.js","BlockNote.js","PostgreSQL","Drizzle ORM","Liveblocks","ElasticSearch","pgvector"],"Hard","16-22 weeks",
      ["Block-based editor (text/h1-h3/todo/code/callout/embed)","Inline databases with multiple views (table/board/gallery/calendar)","Linked mentions","Page hierarchy","Templates","Team workspaces","Full-text search"],
      "Block tree stored as nested nodes with recursive permission inheritance. Live sync via Liveblocks. pgvector for semantic search.",
      "/apps/web\n/apps/server\n/packages/editor\n/packages/database\n/packages/search\n/infra",
      ["BlockNote.js","pgvector","Liveblocks","Claude API"],"PostgreSQL (block tree), pgvector (embeddings), S3 (files)","Railway (backend), Vercel (frontend), Cloudflare R2 (files)",
      "Row-level security in PostgreSQL. Workspace isolation. File upload scanning.","Vertical slice architecture. Block-level lazy loading. CDN for assets.",
      "Block editor internals, recursive data modeling, CRDT, vector search.","Show block editor with database views. Architecture diagram required.","Design block storage tree, recursive permission inheritance, and real-time sync."),

    p("fullstack","advanced","📈","Open-Source Analytics Platform","Self-hosted Plausible/PostHog alternative with privacy-first tracking. Google Analytics 4 is not privacy-compliant in many countries.",
      ["Next.js","ClickHouse","tRPC","Prisma","Chart.js"],"Hard","12-16 weeks",
      ["Script tag embed","Pageview/event tracking","Real-time dashboard","Funnel analysis","Retention cohorts","Custom events","Goal tracking","GDPR-compliant (no cookies)","Public dashboard sharing"],
      "Append-only event log in ClickHouse. Materialized views for aggregations. Script tag embed for tracking. Privacy-first without cookies.",
      "/tracker\n/dashboard\n/api\n/packages/ingest\n/infra",
      ["ClickHouse HTTP API","GeoIP2","ua-parser"],"ClickHouse (events), PostgreSQL (users/sites)","Docker self-hosted + managed cloud",
      "Auth.js authentication. No cookies by default. IP anonymization.","ClickHouse sharding for high-volume sites. CDN for tracker script.",
      "ClickHouse, OLAP queries, tracking pixel design, time-series analysis.","Show real-time dashboard with funnel visualization.","Explain ClickHouse vs PostgreSQL for analytics, materialized views, and GDPR compliance."),

    p("fullstack","production-grade","📋","Linear.app Clone — Engineering PM Tool","Keyboard-first engineering management with Git integration and AI triage. Jira is bloated; Linear's self-hosted option doesn't exist.",
      ["Next.js 14","tRPC","Supabase","Drizzle ORM","GitHub OAuth","Redis"],"Hard","20-28 weeks",
      ["Issues with rich editor","Sprints/cycles","Roadmap view","Git integration (auto-close on merge)","Keyboard shortcuts","Real-time sync","SLA tracking","Metrics dashboard","Slack/GitHub notifications"],
      "Event-sourced issue history. Real-time via Supabase Realtime. Webhook fan-out for Git integration. Optimistic UI updates.",
      "/apps/web\n/apps/api\n/packages/ui\n/packages/engine\n/workers\n/infra",
      ["GitHub API (webhooks/sync)","Slack API","Claude API","Resend"],"PostgreSQL (issues/teams), Redis (real-time), Supabase Realtime","Vercel + Supabase + Railway (background jobs)",
      "Workspace isolation. GitHub token scoping. Webhook HMAC verification.","Read replicas. Optimistic UI. Background sync workers.",
      "Real-time sync, complex data modeling, webhook processing, keyboard UX.","Show keyboard shortcuts and real-time issue updates.","Design event-sourced issue history, real-time sync, and webhook integration."),

    p("fullstack","production-grade","👤","Developer Portfolio Platform (Polywork Clone)","Career timeline platform where developers showcase work not just jobs. LinkedIn is for jobs; GitHub is for code — nothing connects developer impact.",
      ["Next.js","GraphQL (Apollo)","PostgreSQL","Redis","Algolia"],"Hard","16-20 weeks",
      ["Timeline feed","Project showcase","Skills graph","Achievement badges","Team endorsements","Open-to-work signals","Custom domain","Recruiter view"],
      "Profile system with social graph. Algolia for search. GitHub API integration for auto-importing projects. GraphQL for flexible data fetching.",
      "/apps/web\n/apps/api\n/packages/graph\n/packages/search\n/infra",
      ["GitHub API (auto-import)","Twitter API","Stripe"],"PostgreSQL, Redis, Algolia","Vercel + PlanetScale",
      "GitHub OAuth + Auth.js. Custom domain TLS via Cloudflare.","Add feed caching, CDN for profile images, read replicas.",
      "Profile systems, social graphs, search, recommendation algorithms.","Show timeline feed with auto-imported GitHub projects.","Design social graph data model for developer connections and endorsements."),

    p("fullstack","production-grade","💬","Open-Source Customer Support Platform","Self-hosted Intercom — live chat, helpdesk, and knowledge base in one. Intercom/Zendesk are expensive — SMBs need affordable alternatives.",
      ["Next.js","Socket.io","PostgreSQL","Redis","Resend","React"],"Hard","20-28 weeks",
      ["Live chat widget (embeddable)","Ticket management","Team inbox","Auto-assignment rules","Canned responses","Knowledge base","SLA tracking","CSAT surveys","Analytics dashboard","Email integration"],
      "Embeddable widget with cross-origin communication. Socket.io for real-time chat. RAG-based AI suggestions from knowledge base. SLA engine with escalation logic.",
      "/apps/widget\n/apps/dashboard\n/apps/api\n/packages/chat\n/packages/tickets\n/infra",
      ["Socket.io","Resend","Claude API","S3"],"PostgreSQL, Redis (presence/chat)","Docker self-hosted + managed cloud",
      "Auth.js + agent SSO. Widget origin validation. Rate limiting on chat endpoints.","Horizontal Socket.io scaling. Widget CDN distribution. Multi-region.",
      "Embeddable widgets, multi-team inbox, SLA logic, real-time chat.","Show live chat widget working across different origins.","Design multi-tenant chat architecture, SLA engine, and embeddable widget security."),

    // ===== DEVOPS =====
    p("devops","beginner","🐳","Dockerized Full Stack App + CI/CD Pipeline","Multi-service Docker Compose + GitHub Actions that deploys on every push. Most tutorials skip the deployment step entirely.",
      ["Docker","Docker Compose","GitHub Actions","Nginx","bash"],"Easy","2-3 weeks",
      ["Multi-service Compose (app/db/redis/nginx)","GitHub Actions CI/CD","Automated tests","Docker image build + push to GHCR","SSH deploy to VPS","SSL via Let's Encrypt","Health checks"],
      "Multi-stage Dockerfiles for optimized images. GitHub Actions matrix builds. Nginx reverse proxy with Let's Encrypt SSL.",
      "/frontend\n/backend\n/nginx\n/.github/workflows\n/scripts",
      ["GitHub Container Registry","Let's Encrypt","DigitalOcean VPS"],"PostgreSQL container","DigitalOcean / Hetzner VPS",
      "SSH deploy keys in GitHub Secrets. TLS everywhere via Let's Encrypt.","Add blue-green deployment, staging environment, Docker cache optimization.",
      "Docker multi-stage builds, GitHub Actions, Nginx, SSL automation.","Show CI pipeline green with deploy steps.","Explain Docker layers, multi-stage builds, and CI/CD security best practices."),

    p("devops","beginner","📡","Infrastructure Monitoring Dashboard","Self-hosted Datadog lite with Prometheus + Grafana + custom alerts. Developers don't know how to instrument their applications.",
      ["Prometheus","Grafana","Loki","Alertmanager","Node Exporter"],"Easy","2-3 weeks",
      ["App metrics collection","Custom dashboards","Alert rules","Notifications","Uptime monitoring","Log aggregation","SLO tracking"],
      "Prometheus for metrics collection with client libraries. Loki for log aggregation. Grafana for visualization. Alertmanager for routing.",
      "/dashboards\n/rules\n/docker-compose.yml",
      ["Prometheus client libraries","Slack webhook"],"Prometheus TSDB, Loki (logs)","Docker Compose on VPS",
      "Grafana built-in auth. Alertmanager silences. Network isolation.","Add federated Prometheus for multi-region. Long-term storage via Thanos.",
      "Metrics instrumentation, PromQL, Grafana dashboarding, alerting.","Show Grafana dashboard with real application metrics.","Explain RED vs USE metrics, PromQL rate/irate, and alerting best practices."),

    p("devops","intermediate","🧭","Infrastructure as Code Platform","Web UI for managing Terraform workspaces with plan visualization. Raw Terraform CLI is error-prone in teams.",
      ["Go","React","PostgreSQL","S3","Infracost"],"Medium","8-10 weeks",
      ["Workspace management","Plan/apply with visual diff","State file browser","Drift detection","Cost estimation","Approval workflow","Audit log","GitHub integration (plan on PR)","Module registry"],
      "Plan execution as async jobs. State locking via DynamoDB-like mutex. Terraform CLI wrappers for plan/apply. GitOps workflow.",
      "/backend\n/frontend\n/pkg/terraform\n/pkg/state\n/infra",
      ["Terraform CLI/API","Infracost","GitHub API","AWS Cost Explorer"],"PostgreSQL (workspaces/runs), S3 (state)","Kubernetes (Helm chart)",
      "OIDC/SSO. RBAC per workspace. State encryption at rest.","Add remote runners, module registry, policy as code via OPA.",
      "Terraform internals, state management, Go concurrency, GitOps.","Show Terraform plan visualization with cost estimate.","Design Terraform state locking, plan approval workflow, and drift detection."),

    p("devops","intermediate","💰","Kubernetes Cost Optimizer Dashboard","Shows per-pod cloud spend and recommends right-sizing. K8s clusters routinely waste 30-60% of cloud spend.",
      ["Go","Kubernetes API","Prometheus","Grafana","React"],"Medium","8-12 weeks",
      ["Per-namespace/pod cost breakdown","Right-sizing recommendations","Idle workload detection","Auto-scaling suggestions","Savings projections","Slack alerts","Helm value override export"],
      "Kubernetes operator pattern with periodic reconciliation loop. Prometheus for resource metrics. AWS/GCP pricing APIs for cost data.",
      "/operator\n/backend\n/frontend\n/pkg/calculator\n/infra",
      ["K8s metrics-server","Prometheus","AWS/GCP pricing APIs","Helm"],"InfluxDB (metrics), PostgreSQL (config)","Helm chart (into cluster)",
      "Kubernetes RBAC (ServiceAccount). OIDC for dashboard. Read-only access.","Add multi-cluster support, budget alerts, automated remediation.",
      "K8s API, FinOps, resource metrics, cost allocation.","Show cost breakdown per namespace with savings projections.","Explain Kubernetes cost allocation models and right-sizing algorithms."),

    p("devops","intermediate","🔐","Multi-Cloud Secret Manager","Rotate and sync secrets across AWS/GCP/Azure with zero-downtime rotation. Secret sprawl across cloud providers is a major security risk.",
      ["Go","Vault","React","PostgreSQL"],"Medium","8-12 weeks",
      ["Secret CRUD","Automatic rotation","Cross-cloud sync","Access audit log","Environment-based scoping","CLI + API","Emergency break-glass access","Slack notifications"],
      "Vault as backend with cloud provider integrations. Operator pattern for automatic rotation. Audit log for all access. Break-glass workflow for emergencies.",
      "/server\n/cli\n/frontend\n/pkg/vault\n/pkg/providers\n/infra",
      ["AWS Secrets Manager","GCP Secret Manager","Azure Key Vault","HashiCorp Vault"],"PostgreSQL (audit), Vault (secrets)","Kubernetes operator",
      "OIDC + RBAC. Approval gates for prod secrets. Encryption at rest and in transit.","Add auto-scaling, secret caching, DR replica regions.",
      "Secret rotation, cloud IAM, encryption, audit logging.","Show secret rotation with zero-downtime verification.","Design secret rotation strategy with zero-downtime for each cloud provider."),

    p("devops","advanced","🔄","GitOps Platform with Drift Detection","ArgoCD-inspired: Git as truth, auto-sync, drift alerts, multi-cluster. GitOps tooling requires deep K8s expertise to set up correctly.",
      ["Go","Kubernetes","Helm","React","PostgreSQL","controller-runtime"],"Hard","14-18 weeks",
      ["Git repository watching","Auto K8s sync","Drift detection + alerts","One-click rollback","Multi-cluster support","Sync hooks","Visual diff UI","SSO integration","Deployment history"],
      "Custom Application CRD. Controller watches Git + compares live state. Webhook-driven sync on push. Background drift polling.",
      "/controller\n/api\n/frontend\n/pkg/git\n/pkg/diff\n/infra",
      ["controller-runtime","Helm","Kustomize","GitHub API","Slack"],"etcd (via K8s), PostgreSQL (history)","Helm chart into target cluster",
      "OIDC. K8s RBAC. Namespace-scoped permissions. Signed commits.","Multi-cluster kubeconfig management. Cluster discovery.",
      "K8s operator pattern, CRD design, reconciliation loop, GitOps.","Show drift detection alert and one-click rollback.","Explain GitOps reconciliation loop, CRD design, and multi-cluster architecture."),

    p("devops","advanced","🔍","Container Security Scanner","Trivy + Grype-inspired scanner with policy engine and CI/CD integration. Most teams don't scan container images for vulnerabilities before deploy.",
      ["Go","Trivy","PostgreSQL","React","GitHub Actions"],"Medium","10-14 weeks",
      ["Image vulnerability scanning","SBOM generation","Policy enforcement","CI/CD GitHub Action","Dashboard with trend tracking","Slack/JIRA alerts","Base image recommendation"],
      "Integration with Trivy and Grype libraries. Policy engine with Rego-like rules. CI/CD integration via GitHub Actions composite action.",
      "/scanner\n/api\n/frontend\n/pkg/policy\n/action\n/infra",
      ["Trivy","Grype","NIST NVD API","GitHub API"],"PostgreSQL (scan results)","Docker + Helm chart",
      "API keys for CI. OIDC for dashboard. Container isolation for scanning.","Add registry watcher, automated fix PRs, vulnerability SLAs.",
      "Container internals, CVE databases, SBOM, supply chain security.","Show vulnerability report with fix suggestions.","Explain CVE scoring, SBOM generation, and vulnerability policy enforcement."),

    p("devops","production-grade","🏗️","Internal Developer Platform (IDP)","Backstage-inspired self-service portal for engineering teams. Developers waste hours navigating infra, secrets, docs, and deployments.",
      ["React","Go","Vault","Kubernetes","GitHub","Terraform","PostgreSQL"],"Hard","24-36 weeks",
      ["Service catalog","Golden path templates","Secret manager UI","Deployment hub with rollback","Cost explorer","On-call runbooks","Incident timeline","SLO dashboard","Team directory"],
      "Plugin-based module registry. Async job queue for deployments. Secret injection without exposing in UI. Golden path templating engine.",
      "/catalog\n/deployer\n/cost\n/incidents\n/docs\n/notifications\n/infra",
      ["GitHub API","Vault API","PagerDuty","Datadog","Stripe"],"PostgreSQL, Redis, Elasticsearch","Helm chart (enterprise self-hosted)",
      "OIDC/SSO. RBAC per service/team. Secret injection (never exposed in UI).","Microservices per module. GraphQL federation for unified API.",
      "Platform engineering, plugin architecture, golden paths, service mesh.","Flagship infrastructure project. Enterprise saleable.","Design platform engineering architecture, golden path templating, and plugin system."),

    p("devops","production-grade","🎲","Chaos Engineering Platform","Self-hosted Gremlin — inject failures, track blast radius, auto-rollback. Teams discover reliability issues in production instead of tests.",
      ["Go","Kubernetes CRDs","React","Prometheus","Chaos Mesh"],"Hard","16-22 weeks",
      ["Failure injection library (pod kill, network partition, CPU stress, latency)","Experiment designer","Blast radius controls","Auto-rollback triggers","Slack notifications","Hypothesis templates"],
      "Kubernetes CRDs for experiment definitions. Chaos Mesh for failure injection. Prometheus for impact tracking. Auto-rollback on SLO violation.",
      "/controller\n/api\n/frontend\n/pkg/experiments\n/pkg/rollback\n/infra",
      ["Chaos Mesh","Litmus Chaos","Prometheus","Kubernetes API"],"PostgreSQL (history), Prometheus (metrics)","Kubernetes operator (Helm chart)",
      "OIDC, approval gate for production experiments. Namespace-scoped injection.","Add multi-cluster experiments, scheduled resilience tests, game days.",
      "K8s operators, fault injection, observability, reliability engineering.","Show experiment designer and blast radius visualization.","Design chaos experiment lifecycle, blast radius controls, and auto-rollback triggers."),

    p("devops","production-grade","💵","Cloud Cost Intelligence Platform","Pull billing data from all cloud providers — unify, forecast, and act. Multi-cloud companies have no unified view of cloud spending.",
      ["Python","ClickHouse","React","Airflow","dbt"],"Hard","16-24 weeks",
      ["AWS/GCP/Azure billing ingestion","Unified cost dashboard","Anomaly alerts","Tag-based cost allocation","Forecast modeling","Rightsizing recommendations","Showback/chargeback reports","Slack weekly digest"],
      "ETL pipelines via Airflow for cloud billing ingestion. ClickHouse for OLAP queries. dbt for transformations. Forecast modeling with statistical methods.",
      "/ingest\n/transform\n/api\n/frontend\n/dashboards\n/infra",
      ["AWS Cost Explorer","GCP Billing API","Azure Cost API","Stripe"],"ClickHouse, PostgreSQL (metadata)","Kubernetes, managed SaaS",
      "OIDC + per-cloud IAM roles. Cost data encryption. Least-privilege cloud access.","Add multi-account ingestion, scheduled reports, budget alerts.",
      "Cloud billing APIs, data engineering, ClickHouse OLAP, forecasting.","Show cost breakdown with anomaly detection alerts.","Design multi-cloud billing ingestion, cost allocation model, and forecast algorithms."),

    // ===== SECURITY =====
    p("security","beginner","🔑","Password Strength Analyzer","Zxcvbn-powered evaluator with breach lookup and entropy visualization. Most password strength meters are simplistic and misleading.",
      ["React","zxcvbn","HIBP API"],"Easy","2 weeks",
      ["Entropy scoring","Breach check via HIBP (k-anonymity)","Pattern detection (keyboard walks, dates, words)","Policy preset builder","Wordlist attack time estimator"],
      "Client-side React app. zxcvbn for entropy calculation. HIBP API with k-anonymity for breach checking. No passwords leave the browser.",
      "/src\n/src/components\n/src/utils\n/public",
      ["HaveIBeenPwned API (SHA-1 k-anonymity)","zxcvbn"],"None (client-side)","Vercel (static)",
      "k-anonymity ensures passwords never leave the client. No server.","Add password generation, strength over time tracking, enterprise policy engine.",
      "Cryptographic concepts, k-anonymity, entropy math, API integration.","Show entropy visualization and breach check result.","Explain k-anonymity for privacy-preserving breach checking."),

    p("security","beginner","🌐","Network Port Scanner (Nmap Lite)","Browser-accessible port scanner with service detection and reporting. Security beginners need hands-on tools to understand network scanning.",
      ["Python","asyncio","FastAPI","React"],"Easy","3-4 weeks",
      ["TCP/UDP port scan","Service banner grabbing","OS fingerprint hints","Scan profiles (quick/full/stealth)","HTML report export","History log"],
      "Async Python with asyncio for concurrent scanning. FastAPI for REST API. React for report visualization.",
      "/backend\n/frontend\n/pkg/scanner\n/pkg/report",
      ["Python socket library","shodan.io API (optional)"],"SQLite (scan history)","Local Python app only",
      "Local-only deployment for ethical reasons. Rate limiting. User confirmation before scan.","Add CIDR range scanning, vulnerability lookup, nmap integration.",
      "TCP/IP, async Python, socket programming, network protocols.","Show scan results with service detection.","Explain TCP connect vs SYN scan, banner grabbing, and OS fingerprinting."),

    p("security","intermediate","🛡️","Self-Hosted SIEM Lite","Ingest server logs — detect anomalies — alert via Slack. Real SIEM tools cost thousands/month; SMBs need affordable detection.",
      ["Go","ClickHouse","React","Grok parsers"],"Medium","8-10 weeks",
      ["Log ingestion (syslog/auth.log/nginx/Windows Events)","Grok parsing","Detection rules (brute force, priv esc, port scan)","Anomaly scoring","Alert routing","Incident timeline","Threat intel enrichment"],
      "Log pipeline: ingest → parse → enrich → detect → alert. Grok parsing for unstructured logs. ClickHouse for efficient event storage.",
      "/ingester\n/parser\n/detector\n/api\n/frontend\n/infra",
      ["Grok patterns","AbuseIPDB API","Slack webhook","Sigma rules"],"ClickHouse (events), PostgreSQL (rules/alerts)","Docker Compose (self-hosted)",
      "RBAC (analyst/admin roles). Log encryption at rest. Alert deduplication.","Add agent-based log collection, ML anomaly scoring, SOAR integration.",
      "Log parsing, detection rule engineering, MITRE ATT&CK, ClickHouse.","Show SIEM dashboard with alert timeline and MITRE ATT&CK mapping.","Design log pipeline architecture and detection rule engine."),

    p("security","intermediate","🔍","Web Application Vulnerability Scanner","Auto-detect XSS, SQLi, CSRF, SSRF, and exposed secrets. Manual security testing is expensive; automated tools have false positives.",
      ["Python","Playwright","FastAPI","React"],"Medium","8-12 weeks",
      ["Spider/crawler","XSS injection testing","SQL error-based detection","CSRF token analysis","Security header checker","Exposed file detection (.env, .git)","Open redirect testing","Detailed HTML report"],
      "Async scan workers with Playwright for headless crawling. Deduplication engine for results. Report generation with fix recommendations.",
      "/scanner\n/api\n/frontend\n/pkg/crawler\n/pkg/monitor\n/infra",
      ["Playwright","BeautifulSoup","SQLMap (reference)","OWASP check libs"],"PostgreSQL (scan results)","Docker + Vercel (report UI)",
      "API key for SaaS version. Rate limiting. No payloads on untrusted targets.","Add authenticated scanning, CI/CD integration, continuous monitoring.",
      "Web security, headless browser automation, OWASP Top 10.","Show scan report with verified findings.","Explain XSS/SQLi detection techniques and false positive reduction."),

    p("security","intermediate","🏴‍☠️","CTF Challenge Platform","Self-hosted HackTheBox lite with Docker-based isolated challenge environments. Security students need hands-on labs without paying HackTheBox fees.",
      ["Next.js","Go","Docker API","PostgreSQL","Redis"],"Medium","10-14 weeks",
      ["Challenge categories (web/crypto/pwn/forensics/misc)","Docker sandbox per user","Automated flag checking","Scoreboard","Team mode","Hints system","Writeup submission","Admin challenge builder"],
      "Docker API for per-user container orchestration. WebSocket terminal via xterm.js. Automated flag checking with rotation.",
      "/frontend\n/challenge-runner\n/api\n/pkg/docker\n/pkg/flags\n/infra",
      ["Docker API","WebSocket terminal (xterm.js)","Judge0"],"PostgreSQL, Redis (sessions/leaderboard)","VPS with Docker socket",
      "Container isolation per user. Resource limits. Network restrictions.","Add PvP mode, live challenges, hint analytics.",
      "Docker containerization, security challenge design, WebSocket terminal.","Show scoreboard and challenge categories.","Design isolated container architecture per challenge per user."),

    p("security","advanced","🔐","Zero Trust Access Proxy","Cloudflare Access-inspired identity-aware proxy for internal apps. VPNs are cumbersome — Zero Trust is the modern approach but complex to build.",
      ["Go","Envoy Proxy","OPA","SPIRE","React"],"Hard","16-20 weeks",
      ["mTLS client certificate auth","OIDC identity verification","Device posture checks","Per-application policies","Short-lived certs via SPIFFE","Audit log","Admin panel","SSH/TCP proxying","Browser-based access"],
      "Identity-aware proxy layer with Envoy. Short-lived cert issuance via SPIRE/SPIFFE. OPA for policy evaluation. Continuous verification.",
      "/proxy\n/control-plane\n/policy-engine\n/api\n/frontend\n/infra",
      ["OIDC","mTLS","SPIFFE/SPIRE","OPA Rego","Envoy xDS API"],"PostgreSQL (policies/audit), etcd (config)","Kubernetes",
      "Defense in depth. No implicit trust. Continuous verification. mTLS everywhere.","Add device trust integration, SOAR connector, geo-fencing.",
      "Zero Trust, mTLS, SPIFFE, Envoy xDS, OPA policy language.","Show access flow diagram with policy evaluation steps.","Design Zero Trust architecture with SPIFFE identity and OPA policy evaluation."),

    p("security","advanced","🔎","Secrets Detection CI/CD Tool","Pre-commit hook + CI scanner that catches credentials before they ship. Leaked secrets in git repos cause millions in breaches annually.",
      ["Python","Rust (PyO3)","React","FastAPI","PostgreSQL"],"Hard","8-12 weeks",
      ["200+ regex patterns (AWS keys, GitHub tokens, private keys, etc.)","Git pre-commit hook","GitHub Actions integration","Baseline management","False positive training","Audit report","Slack/JIRA notifications"],
      "Regex engine performance optimized with Rust via PyO3. Git hooks for pre-commit scanning. GitHub App integration for PR scanning.",
      "/scanner\n/api\n/frontend\n/hooks\n/github-app\n/infra",
      ["GitHub API (webhooks)","GitLab API","Slack"],"PostgreSQL (scan results, baselines)","GitHub Marketplace + pip",
      "GitHub App OAuth. No false positive data shared. Local-first scanning.","Add ML-based false positive reduction, custom pattern builder.",
      "Regex engines, git hooks, GitHub App development, Rust/Python.","Show detection finding with false positive management.","Design regex scanning engine for performance and false positive reduction."),

    p("security","production-grade","🧠","AI-Powered Threat Intelligence Platform","Aggregate threat feeds — enrich IOCs — AI-generated threat reports. Security teams drown in raw threat data with no synthesis layer.",
      ["Python","Kafka","Elasticsearch","React","Claude API"],"Hard","24-32 weeks",
      ["Multi-feed ingestion (MISP/OTX/VirusTotal/Shodan)","IOC enrichment","Threat actor correlation","MITRE ATT&CK auto-mapping","Hunt query generator","AI threat report generation","Alert integration with SIEMs","Sharing community"],
      "Event-driven IOC processing pipeline on Kafka. Graph model for actor attribution. Elasticsearch for search and correlation. AI for report generation.",
      "/ingest\n/enrich\n/correlate\n/report-gen\n/api\n/frontend\n/infra",
      ["MISP","AlienVault OTX","VirusTotal","Shodan","Cortex","OpenCTI"],"Elasticsearch (IOCs/reports), PostgreSQL (config), Redis (cache)","Kubernetes, multi-region",
      "RBAC with TLP data classification. Air-gapped deployment option.","Add real-time feed streaming, automated feed curation, CTI sharing hub.",
      "CTI analysis, graph databases, Elasticsearch, Kafka, STIX/TAXII.","Enterprise CTI platform. Show threat actor graph and AI report.","Design CTI pipeline architecture with STIX/TAXII, IOC enrichment, and threat scoring."),

    // ===== AI =====
    p("ai","beginner","📄","PDF Chat Assistant","Upload any PDF — chat with it using RAG with cited page references. Reading dense documents (legal/research/manuals) takes hours.",
      ["Python","LangChain","ChromaDB","FastAPI","React","Claude API"],"Easy","2-3 weeks",
      ["PDF upload","Text extraction","Chunking","Embedding","Vector search","Streaming chat responses","Source citation with page numbers","Conversation history","Multi-PDF support"],
      "RAG pipeline: PDF text extraction → chunking → embedding → vector store. ChromaDB for vector similarity search. Streaming responses with citations.",
      "/backend\n/frontend\n/pkg/rag\n/pkg/ingest\n/pkg/embeddings",
      ["Claude API","LangChain","ChromaDB","PyPDF2"],"ChromaDB (vectors), PostgreSQL (conversations)","Railway / Render",
      "File upload validation. No document retention after session.","Add document collections, cross-document Q&A, OCR for scanned PDFs.",
      "RAG architecture, text chunking strategies, embedding models, vector search.","Show RAG response with page-level citations.","Explain chunking strategies, embedding model selection, and hybrid search."),

    p("ai","beginner","🎙️","AI Meeting Notes Summarizer","Upload meeting audio/transcript — get structured notes with action items. Meeting notes are inconsistent and action items fall through cracks.",
      ["Python","OpenAI Whisper","Claude API","FastAPI","React"],"Easy","3-4 weeks",
      ["Audio upload (Whisper transcription)","Speaker diarization","Structured output (summary/decisions/action items/owners)","Slack/Notion export","Calendar integration","Searchable history"],
      "Whisper for audio transcription. Claude API for structured summarization. Speaker diarization for attribution. Webhook integrations for Slack/Notion.",
      "/backend\n/frontend\n/pkg/transcribe\n/pkg/summarize\n/pkg/export",
      ["Whisper API","Claude API","Slack API","Notion API"],"PostgreSQL (meetings/notes)","Vercel (frontend), Railway (API)",
      "Google OAuth. Audio file encryption. Meeting data retention policies.","Add live transcription via WebSocket, action item tracking, calendar sync.",
      "Audio processing, Whisper, structured output, webhook integrations.","Show structured notes with action items and speaker labels.","Explain Whisper transcription, speaker diarization, and structured output parsing."),

    p("ai","intermediate","🤖","AI Code Review Bot (GitHub App)","GitHub App that reviews PRs using Claude — posts inline review comments. Code review is bottlenecked on senior engineers.",
      ["Node.js","GitHub App API","Claude API","Octokit","PostgreSQL"],"Medium","4-6 weeks",
      ["Auto PR review on open/update","Inline comments on specific lines","Security anti-pattern detection","Performance issue flagging","Test coverage gap identification","Configurable review rules"],
      "Webhook → queue → review worker → GitHub API flow. Multi-pass review: security → bugs → style → tests. Diff parsing for line-level comments.",
      "/webhook\n/worker\n/api\n/frontend\n/pkg/reviewer\n/infra",
      ["GitHub App SDK","Claude API","GitHub REST API"],"PostgreSQL (history, repo configs)","Railway + GitHub Marketplace",
      "GitHub App OAuth installation. Token-scoped permissions.","Add auto-fix PRs, review rule learning from human feedback.",
      "GitHub App dev, webhook processing, diff parsing, structured AI output.","Show inline PR review comments from AI.","Design multi-pass review pipeline and GitHub App webhook architecture."),

    p("ai","intermediate","🔬","Multi-Agent Research Assistant","Orchestrate specialized AI agents to produce deep research reports. LLM hallucination rates are high for complex research — agents verify.",
      ["Python","LangGraph","Claude API","Tavily Search","FastAPI","React"],"Medium","6-8 weeks",
      ["Multi-agent pipeline (planner/searcher/summarizer/critic/writer)","Web search integration","Source verification","Citation management","Streaming progress updates","Export to Notion/PDF","Report history"],
      "State machine per research task using LangGraph. Parallel agent execution. Human-in-the-loop approval before final report.",
      "/backend\n/frontend\n/agents\n/pkg/tools\n/pkg/memory",
      ["Claude API","Tavily API","Jina Reader API","LangGraph"],"PostgreSQL (reports, sessions)","Railway (API), Vercel (UI)",
      "Auth.js authentication. Citation verification. Rate limiting on search.","Add custom knowledge base integration, multi-language support.",
      "Agent orchestration, graph-based workflows, tool use, prompt engineering.","Show real-time agent progress streaming with citations.","Design multi-agent state machine with human-in-the-loop approval."),

    p("ai","intermediate","🎤","Voice AI Assistant SDK","Build your own Alexa/Siri voice assistant framework as a developer SDK. Building voice assistants requires stitching many services.",
      ["Python","Whisper","Claude API","ElevenLabs TTS","WebRTC"],"Medium","8-12 weeks",
      ["Wake word detection","Real-time STT (Whisper)","LLM response","TTS (ElevenLabs/Azure)","Conversation memory","Tool calling","Streaming audio pipeline","Developer SDK (Python/Node/React)"],
      "Real-time streaming pipeline: audio → VAD → STT → LLM → TTS → audio out. WebRTC for browser audio. PyAudio for desktop.",
      "/sdk/python\n/sdk/node\n/sdk/react\n/server\n/examples",
      ["Whisper","Claude API","ElevenLabs","PyAudio","WebRTC"],"Redis (conversation state), PostgreSQL (user data)","PyPI + Docker",
      "API key authentication. Audio data encryption. No voice data retention.","Add custom wake word, emotion detection, multi-language support.",
      "Real-time audio streaming, VAD, streaming pipeline latency, WebRTC.","Show voice assistant responding with personality config.","Design real-time audio pipeline and streaming latency optimization strategies."),

    p("ai","advanced","🧠","AI Memory Operating System","Persistent hierarchical memory layer for LLM agents — like human memory. LLM agents forget everything between sessions.",
      ["Python","pgvector","Redis","Claude API","LangGraph","FastAPI"],"Hard","12-16 weeks",
      ["Short-term working memory (context window)","Episodic memory with decay","Semantic memory (fact store)","Procedural memory (learned patterns)","Memory consolidation","Importance weighting","Cross-session retrieval"],
      "4-tier memory architecture. Nightly consolidation job. Hybrid sparse+dense retrieval. LLM-driven memory compression and importance scoring.",
      "/memory/core\n/memory/episodic\n/memory/semantic\n/memory/procedural\n/api\n/sdk",
      ["pgvector","Redis","Claude API","scikit-learn (clustering)"],"PostgreSQL + pgvector (semantic), Redis (working)","PyPI SDK + hosted API",
      "API key authentication. Memory isolation per user/agent. Data retention policies.","Add memory sharing between agents, federated memory, graph memory.",
      "Memory system design, vector similarity, LLM summarization, temporal data.","Novel research-level idea. Show memory hierarchy working.","Design 4-tier memory architecture with consolidation and importance scoring."),

    p("ai","advanced","🎯","LLM Fine-Tuning Pipeline Platform","Upload datasets, configure LoRA jobs, monitor training, deploy models. Fine-tuning LLMs requires deep ML expertise and painful infra setup.",
      ["Python","Hugging Face Transformers","PEFT (LoRA)","FastAPI","React","Modal"],"Hard","14-18 weeks",
      ["Dataset upload + validation","Training job config (LoRA/QLoRA)","Training loss visualization","Eval benchmark runner","Model comparison","One-click deploy to vLLM","Model versioning"],
      "Async training job queue. Streaming loss metrics via WebSocket. Model versioning with registry. vLLM for efficient serving.",
      "/backend\n/frontend\n/pkg/trainer\n/pkg/eval\n/pkg/serving\n/infra",
      ["Hugging Face Hub","Weights & Biases","Modal","vLLM"],"PostgreSQL (jobs/models), S3 (datasets/checkpoints)","GPU cloud (Modal/Lambda Labs)",
      "Auth.js + API keys. Dataset access controls. Model security scanning.","Add distributed training, RLHF support, model A/B testing.",
      "LoRA/QLoRA, gradient checkpointing, distributed training, vLLM.","Show training loss curves and model comparison dashboard.","Design LoRA training pipeline, data validation, and model serving architecture."),

    p("ai","production-grade","🤖","Autonomous AI Software Engineer","Give it a GitHub issue — it reads code, plans, writes, tests, opens PR. Junior developer work (bug fixes, small features) is automatable.",
      ["Python","Claude API","LangGraph","GitHub API","Docker"],"Hard","20-30 weeks",
      ["GitHub issue intake","Codebase RAG (repo indexing)","Planning step","Tool-using agent (read/write/execute/test)","Reflection loop","PR creation with description","Code review response handling","Human approval gate"],
      "Hierarchical agent: task planner → sub-agents → synthesizer. Docker sandbox for safe code execution. Approval gate before destructive actions.",
      "/agent/planner\n/agent/workers\n/agent/reflector\n/sandbox\n/api\n/dashboard\n/infra",
      ["Claude API","GitHub API","tree-sitter (code parsing)","pytest/jest runners"],"PostgreSQL (tasks/history), pgvector (code embeddings)","Railway (workers), Vercel (dashboard), Docker (sandbox)",
      "Sandboxed execution. Restricted filesystem. No secrets access. Human-in-loop.","Add PR review handling, multiple repo support, learning from past tasks.",
      "Agentic system design, code execution sandboxing, long-horizon planning.","Flagship AI project. Show agent resolving a real GitHub issue.","Design hierarchical agent architecture with sandboxed execution."),

    p("ai","production-grade","🎨","AI Prompt Engineering Studio","Test, compare, and optimize prompts across models with analytics. Prompt engineering is unscientific — no tooling for systematic testing.",
      ["Next.js","tRPC","PostgreSQL","Claude API","OpenAI API","Gemini API"],"Hard","12-16 weeks",
      ["Prompt editor with variables","Multi-model comparison (Claude/GPT/Gemini)","A/B testing","Scoring rubrics","Version history","Team collaboration","Cost tracking per prompt/run","Prompt library marketplace"],
      "Multi-model API integration layer. A/B testing system with statistical significance. Cost tracking and prompt versioning.",
      "/apps/web\n/apps/api\n/packages/models\n/packages/eval\n/packages/billing",
      ["Claude API","OpenAI API","Google Gemini","Anthropic streaming"],"PostgreSQL (prompts/results), S3 (large outputs)","Vercel + Railway",
      "Auth.js + team workspaces. API key management. Cost budgets per team.","Add prompt injection detection, regression testing, auto-optimizer.",
      "Multi-model API integration, A/B testing systems, eval frameworks.","Show prompt comparison with scoring rubric.","Design multi-model comparison framework and A/B testing for prompts."),

    p("ai","production-grade","📄","Multimodal AI Document Intelligence","Extract structured data from any document — invoices, contracts, forms. Enterprises manually process millions of documents — extremely costly.",
      ["Python","Claude (vision)","FastAPI","React","Celery","PostgreSQL"],"Hard","16-22 weeks",
      ["PDF/image ingestion","Layout-aware extraction","Table extraction","Handwriting OCR","Custom extraction schema builder","Webhook output","Confidence scores","Human review queue"],
      "Vision LLM for layout understanding. Schema-guided extraction with structured output. Async job processing via Celery. Human-in-loop for low confidence.",
      "/ingest\n/api\n/frontend\n/pkg/extract\n/pkg/review\n/infra",
      ["Claude API (vision)","AWS Textract (backup)","S3","Celery"],"PostgreSQL (extractions), S3 (documents), Redis (job queue)","Kubernetes, multi-region S3",
      "API keys + RBAC for review portal. Document encryption at rest. PII redaction.","Add custom extraction model training, real-time extraction API.",
      "Document AI, vision models, async job processing, schema design.","Show extraction result with confidence scoring and review queue.","Design document intelligence pipeline with vision LLM and schema-guided extraction."),

    // ===== DATA-AI (ML / Data Science / Data Engineering) =====
    p("data-ai","beginner","📈","Stock Sentiment Analyzer","Scrape financial news + Reddit — correlate sentiment with price movements. Retail investors have no systematic way to track market sentiment.",
      ["Python","FinBERT","yfinance","PRAW","Streamlit"],"Easy","3-4 weeks",
      ["Reddit/news scraping","FinBERT sentiment scoring","Price correlation charts","Ticker watchlist","Daily sentiment digest email","Historical backtesting"],
      "FinBERT NLP pipeline for sentiment scoring. yfinance for price data. Correlation analysis with backtesting.",
      "/scraper\n/analyzer\n/dashboard\n/notebooks",
      ["Reddit API","Alpha Vantage","FinBERT (HuggingFace)","Streamlit"],"PostgreSQL, Parquet files","Streamlit Cloud / Hugging Face Spaces",
      "None (personal tool). API key management for data sources.","Add real-time streaming, paper trading integration, sentiment alerts.",
      "NLP, financial data, sentiment analysis, time-series correlation.","Show sentiment vs price correlation chart.","Explain FinBERT fine-tuning and sentiment-price correlation methodology."),

    p("data-ai","beginner","📊","Customer Churn Predictor","Upload SaaS event data — train churn model — get at-risk customer list. SaaS companies lose revenue identifying churned customers too late.",
      ["Python","XGBoost","SHAP","Streamlit","pandas","scikit-learn"],"Easy","3-5 weeks",
      ["Data upload (CSV/Parquet)","Automated feature engineering","XGBoost model","SHAP explainability charts","At-risk dashboard","Cohort analysis","Export"],
      "ML pipeline with feature engineering, XGBoost classifier, SHAP explanations. Streamlit for interactive dashboard.",
      "/pipeline\n/dashboard\n/notebooks\n/models",
      ["SHAP","Optuna (hyperparameter tuning)","Streamlit"],"SQLite / uploaded files","Streamlit Cloud",
      "None (uploaded data processed locally).","Add automated retraining, real-time prediction API, CRM integration.",
      "ML pipeline, feature engineering, class imbalance, model explainability.","Show SHAP explanation for individual customer churn reasons.","Explain XGBoost handling of class imbalance and SHAP for model interpretability."),

    p("data-ai","intermediate","⚡","Real-Time ML Feature Store","Feast-inspired feature store with online/offline storage and serving API. ML teams duplicate feature computation across training and inference.",
      ["Python","Redis","Apache Parquet","FastAPI","dbt","DuckDB"],"Medium","8-12 weeks",
      ["Feature registry with versioning","Online store (Redis — low latency)","Offline store (Parquet/BigQuery)","Point-in-time joins for training data","Data freshness SLAs","REST serving API","Python SDK"],
      "Write path: batch compute → offline → online sync. Read path: online Redis for sub-5ms p99 latency. Point-in-time join logic for training data.",
      "/registry\n/online\n/offline\n/sdk\n/api\n/infra",
      ["Redis","Great Expectations","DuckDB","Arrow"],"Redis (online), Parquet/DuckDB (offline), PostgreSQL (registry)","Docker Compose",
      "API key authentication. Feature-level access control. Data lineage tracking.","Add streaming feature computation, feature drift monitoring, auto-scaling.",
      "Feature engineering, online/offline duality, point-in-time joins, low-latency serving.","Show feature serving latency and point-in-time join correctness.","Design feature store architecture with online/offline serving and point-in-time joins."),

    p("data-ai","intermediate","🖼️","Computer Vision Defect Detector","Upload product images — YOLOv8 detects manufacturing defects in real-time. Manual quality inspection is slow, inconsistent, and expensive.",
      ["Python","YOLOv8","FastAPI","React","PostgreSQL","Roboflow"],"Medium","6-10 weeks",
      ["Real-time image upload and inference","Bounding box visualization","Defect severity scoring","Batch processing","PDF inspection reports","Model retraining from corrections","Alert webhooks"],
      "YOLOv8 object detection pipeline. ONNX export for edge inference. Active learning loop from human corrections. S3 for image storage.",
      "/api\n/frontend\n/pkg/detector\n/pkg/trainer\n/pkg/report\n/infra",
      ["Ultralytics YOLOv8","Roboflow","OpenCV","S3"],"PostgreSQL (inspections), S3 (images)","Docker + edge deployment (ONNX)",
      "API key (factory) + dashboard login. Image validation. Edge-only deployment option.","Add multi-camera support, real-time video stream, automated retraining pipeline.",
      "Object detection, transfer learning, data labeling, model deployment.","Show defect detection with bounding box and severity score.","Explain YOLOv8 architecture, transfer learning for custom defects, and edge deployment."),

    p("data-ai","intermediate","🧪","A/B Testing Platform","Self-hosted Optimizely — run experiments with statistical significance. Optimizely/LaunchDarkly are expensive; most teams have no testing rigor.",
      ["Go","Python","React","PostgreSQL","Redis","ClickHouse"],"Medium","10-14 weeks",
      ["Experiment designer","User bucketing","Variant assignment","Metric tracking","Bayesian/frequentist significance testing","Early stopping rules","Visual results dashboard","SDK for JS/Python/Go"],
      "Go assignment engine for low-latency bucketing. Python for statistical computations. ClickHouse for event storage. Redis for assignment cache.",
      "/engine\n/stats\n/api\n/sdks\n/dashboard\n/infra",
      ["scipy (stats)","ClickHouse"],"PostgreSQL (experiments), ClickHouse (events), Redis (assignment)","Docker self-hosted + managed cloud",
      "Auth.js + SDK API keys. Assignment consistency guarantees.","Add multi-armed bandit, ML-driven optimization, rollback automation.",
      "Statistics (Bayesian A/B), experimentation design, bucketing algorithms.","Show experiment results with significance visualization.","Explain Bayesian vs frequentist significance testing and early stopping rules."),

    p("data-ai","advanced","🧬","End-to-End ML Platform (mini MLflow)","Experiment tracking, model registry, HP tuning, A/B deployment. ML teams use 5 different tools — no unified platform.",
      ["Python","PostgreSQL","MinIO","Ray Tune","React","FastAPI"],"Hard","16-22 weeks",
      ["Experiment + metric tracking","Model versioning registry","Artifact storage","Hyperparameter tuning UI (Optuna/Ray)","A/B model deployment (canary)","Data drift monitoring","Model performance degradation alerts"],
      "Pluggable artifact store. Model registry with stage transitions. Prediction service router for A/B traffic splitting. Evidently for drift detection.",
      "/registry\n/tracker\n/tuner\n/serving\n/api\n/frontend\n/infra",
      ["Optuna","Evidently","MLflow Python client (compatible)"],"PostgreSQL (metadata), MinIO (artifacts), TimescaleDB (metrics)","Kubernetes (Helm chart)",
      "RBAC (experimenter/deployer/admin). Model access audit. Artifact encryption.","Add auto-ML, model monitoring dashboard, pipeline orchestration.",
      "MLOps, experiment tracking, model serving, artifact versioning, drift detection.","Show experiment comparison and model registry workflow.","Design full MLOps platform with experiment tracking, model registry, and canary serving."),

    p("data-ai","advanced","🎵","Recommendation Engine Platform","Build Spotify's recommendation system as a reusable platform. Every product needs personalization but building RecSys is hard.",
      ["Python","PyTorch","Implicit (ALS)","FastAPI","React","PostgreSQL"],"Hard","12-16 weeks",
      ["User-item interaction ingestion","Collaborative filtering (ALS)","Content-based filtering","Hybrid ranking","A/B testing for strategies","Embedding visualization","API serving"],
      "Matrix factorization with ALS. Two-tower retrieval model. ANN search via FAISS/Qdrant. Cold-start handling with LLM.",
      "/api\n/frontend\n/pkg/als\n/pkg/two-tower\n/pkg/hybrid\n/pkg/vectors",
      ["Implicit library","Annoy/FAISS (ANN search)","Weights & Biases"],"PostgreSQL (interactions), Redis (cache), Qdrant (vectors)","Docker + Kubernetes (GPU node)",
      "API key authentication. User data anonymization. Rate limiting.","Add real-time personalization, multi-modal recommendations, exploration framework.",
      "Collaborative filtering, matrix factorization, ANN search, cold-start.","Show recommendation quality metrics and embedding visualization.","Design hybrid recommendation system with ALS, two-tower model, and cold-start handling."),

    p("data-ai","production-grade","🕵️","Real-Time Fraud Detection System","Stream payments — GNN + XGBoost fraud scorer — sub-50ms decisions. Payment fraud costs $40B+ annually.",
      ["Python","Kafka","Apache Flink","PyTorch Geometric","XGBoost","Redis","Grafana"],"Hard","20-28 weeks",
      ["Kafka event ingestion","Flink real-time feature computation","Redis feature lookup","GNN (fraud ring detection)","XGBoost scorer","SHAP explanations","Analyst dashboard","Rule override system"],
      "Lambda architecture — real-time scoring + batch model retraining. Feature freshness guarantees. Fallback rules when model fails. GNN detects fraud rings.",
      "/ingest\n/features\n/models\n/scoring\n/api\n/dashboard\n/infra",
      ["Kafka Streams","Flink Python API","PyTorch Geometric","SHAP"],"Redis (features), PostgreSQL (decisions), ClickHouse (analytics)","Kubernetes (GPU node), Kafka cluster",
      "PII masking. Model access controls. Audit trail. Model explainability.","Add explainable AI for declined transactions, real-time model retraining.",
      "Real-time ML, graph neural networks, streaming features, model serving latency.","Flagship ML project. Show fraud detection with SHAP explanations.","Design real-time fraud detection architecture with GNN and XGBoost."),

    // ===== BLOCKCHAIN =====
    p("blockchain","beginner","🗳️","On-Chain Voting System","Tamper-proof voting dApp with wallet auth and public result verification. Traditional voting systems lack transparency and tamper-resistance.",
      ["Solidity","Hardhat","ethers.js","React","IPFS"],"Easy","3-4 weeks",
      ["Wallet connection (MetaMask)","Proposal creation","Time-locked voting","Token-weighted votes","Vote delegation","Public result verification","IPFS-stored metadata"],
      "Smart contract with vote storage on-chain. IPFS for proposal metadata. Hardhat for testing and deployment.",
      "/contracts\n/frontend\n/test\n/scripts",
      ["MetaMask","Infura/Alchemy","IPFS/Filecoin","Hardhat"],"Blockchain (votes), IPFS (proposals)","Ethereum testnet (Sepolia) → mainnet",
      "Wallet signature (MetaMask). Gas limit protection. Vote encryption.","Add quadratic voting, anonymous voting via ZK proofs, DAO integration.",
      "Solidity basics, contract testing, wallet integration, IPFS.","Show voting UI with public verifiability.","Explain on-chain voting security, Sybil resistance, and gas optimization."),

    p("blockchain","beginner","🎨","NFT Minting Platform","Upload art — mint ERC-721 NFT with royalties and gallery frontend. Artists need no-code tools to mint NFTs.",
      ["Solidity","Hardhat","React","ethers.js","IPFS/Pinata"],"Easy","3-4 weeks",
      ["IPFS upload","ERC-721 minting","EIP-2981 royalty standard","Gallery view","Collection management","OpenSea-compatible metadata","Listing interface"],
      "ERC-721 contract with EIP-2981 royalties. IPFS for metadata and images. OpenSea-compatible metadata format.",
      "/contracts\n/frontend\n/scripts\n/test",
      ["Pinata (IPFS)","OpenSea API","Alchemy"],"IPFS (metadata), blockchain (ownership)","Polygon (low fees)",
      "Wallet authentication. Royalty enforcement on marketplace.","Add generative NFT collection, staking, NFT marketplace.",
      "ERC-721, IPFS, NFT metadata standards, royalty mechanics.","Show NFT gallery with minting flow.","Explain ERC-721, EIP-2981 royalties, and IPFS metadata standards."),

    p("blockchain","intermediate","💰","DeFi Yield Aggregator","Auto-compound yields across Aave/Compound/Curve — one-click optimization. DeFi users leave money on the table by not optimizing yield.",
      ["Solidity","Foundry","Uniswap SDK","The Graph","React","ethers.js"],"Hard","10-14 weeks",
      ["Multi-protocol APY comparison","One-click migration","Auto-compounding","Risk scoring per vault","Portfolio dashboard","Gas optimization","Emergency withdrawal","Performance fee tracking"],
      "Vault contract pattern with strategy pattern for swappable yield sources. Formal verification with Certora. Flash loan integration.",
      "/contracts/vaults\n/contracts/strategies\n/frontend\n/subgraph\n/test",
      ["Aave API","Compound API","Curve API","The Graph"],"The Graph (indexed), PostgreSQL (dashboard)","Ethereum mainnet (requires audit)",
      "Formal verification. Reentrancy guards. Time locks. Multi-sig admin.","Add cross-chain vaults, automated rebalancing, yield optimization AI.",
      "DeFi protocols, yield optimization, on-chain math, flash loans, gas optimization.","Show APY comparison and portfolio dashboard.","Design yield aggregation strategy pattern with formal verification."),

    p("blockchain","intermediate","🔍","Smart Contract Auditing Platform","Upload Solidity — auto-detect vulnerabilities with line-level explanations. Smart contract audits cost $20k-200k — teams ship unaudited code.",
      ["Python","Slither","Mythril","Claude API","React","FastAPI"],"Medium","8-12 weeks",
      ["Solidity file upload","Static analysis (reentrancy/overflow/access)","Symbolic execution","Fuzzing integration","Severity scoring","Fix suggestions","Audit report PDF","CI/CD GitHub Action"],
      "Async analysis jobs with parallel tool execution (Slither + Mythril + Echidna). AI for vulnerability explanation and fix suggestions.",
      "/scanner\n/api\n/frontend\n/action\n/pkg/analyzers\n/infra",
      ["Slither","Mythril","Echidna (fuzzing)","Claude API","Foundry"],"PostgreSQL (audit results)","Docker + Railway",
      "API key / GitHub OAuth. Smart contract sandboxing. Read-only analysis.","Add formal verification, upgradeability checks, custom rule engine.",
      "Smart contract security, Slither/Mythril internals, EVM, SWC registry.","Show vulnerability report with line-level AI explanations.","Explain static analysis vs symbolic execution vs fuzzing for smart contract audits."),

    p("blockchain","intermediate","🤝","Decentralized Escrow Service","Smart contract escrow for freelancer payments with dispute resolution. Freelancers have no trustless payment mechanism.",
      ["Solidity","Hardhat","React","ethers.js","The Graph"],"Medium","8-10 weeks",
      ["Escrow creation with milestones","Dispute raising","Arbitrator selection (Kleros)","Refund logic","Multi-token support","Reputation system","Frontend dashboard"],
      "Escrow contract with milestone-based release. Kleros integration for arbitration. Chainlink oracle for external data. Reputation tracking via events.",
      "/contracts\n/frontend\n/subgraph\n/test",
      ["Kleros (arbitration)","Chainlink (oracle)","IPFS (contract terms)"],"IPFS (terms), blockchain (state)","Polygon (low fees)",
      "Time-locked withdrawals. Multi-sig for dispute resolution. Reentrancy protection.","Add insurance pool, automated dispute resolution, DAO governance.",
      "Contract design patterns, time locks, multi-sig, oracle usage.","Show escrow flow with milestone tracking.","Design escrow contract with dispute resolution and oracle integration."),

    p("blockchain","advanced","🔄","DEX (Decentralized Exchange) Lite","Build a Uniswap v2 AMM clone with liquidity pools and swap UI. Understanding AMMs requires building one from scratch.",
      ["Solidity","Foundry","React","ethers.js","The Graph"],"Hard","14-18 weeks",
      ["AMM constant product formula (x*y=k)","Liquidity provision/removal","Token swaps with slippage","Price impact display","LP token minting","Fee distribution","Price charts via events"],
      "Uniswap v2 pattern: Pair contracts, factory contract, router contract. Foundry for formal invariant testing. The Graph for event indexing.",
      "/contracts/core\n/contracts/periphery\n/frontend\n/subgraph\n/test",
      ["Uniswap v2 reference","Foundry fuzzing tests"],"Blockchain, The Graph","Ethereum testnet → Polygon/Arbitrum",
      "Slippage protection. Oracle manipulation resistance. Formal invariant testing.","Add limit orders, concentrated liquidity, TWAP oracles.",
      "AMM math, liquidity pool mechanics, Foundry testing, The Graph.","Show swap interface with price impact visualization.","Explain AMM constant product formula, impermanent loss, and MEV protection."),

    p("blockchain","advanced","🏛️","DAO Governance Framework","OpenZeppelin Governor-based DAO with treasury and on-chain execution. DAOs need battle-tested governance.",
      ["Solidity","OpenZeppelin Governor","Foundry","React","The Graph"],"Hard","12-16 weeks",
      ["Proposal creation","Timelock execution","Token-weighted voting","Quorum rules","Treasury management","Grant disbursement proposals","Snapshot integration","Multi-sig guardians"],
      "OpenZeppelin Governor pattern with Compound Timelock. Token delegation. On-chain proposal execution with timelock delays.",
      "/contracts\n/frontend\n/subgraph\n/test",
      ["OpenZeppelin Governor","Compound Timelock","Snapshot.org API"],"Blockchain, The Graph, IPFS","Ethereum mainnet (after audit)",
      "Timelock delays. Multi-sig guardians. Quorum validation. Proposal cancellation.","Add quadratic voting, delegation pools, conviction voting.",
      "Governor pattern, timelock, token delegation, on-chain execution.","Show proposal creation and voting flow.","Design DAO governance with timelock security and quorum mechanics."),

    p("blockchain","production-grade","🔐","ZK Identity and Credentials Protocol","Prove age/credentials without revealing identity via ZK proofs. Web3 apps need identity verification without privacy violations.",
      ["Circom","SnarkJS","Solidity","React","Polygon"],"Hard","24-36 weeks",
      ["Credential issuance (off-chain signed)","ZK proof generation in browser","Smart contract verifier","Use cases (age gate/KYC/degree)","SDK for dApps","Revocation mechanism","Cross-chain verification"],
      "Circom ZK circuits with Groth16/PLONK provers. Browser-based proof generation. Solidity verifier contracts. Revocation via nullifiers.",
      "/circuits\n/contracts\n/sdk\n/frontend\n/test",
      ["Circom","SnarkJS","Groth16/PLONK provers","IPFS"],"Blockchain (verified claims), IPFS (schemas)","Polygon PoS (low fees)",
      "No personal data on-chain. Proof soundness guarantees. Revocation via nullifiers.","Add recursive proofs, multi-credential aggregation, zk-email.",
      "ZK circuit design, Groth16/PLONK, trusted setup, Circom DSL.","Cutting-edge cryptography project. Show ZK proof generation in browser.","Design ZK identity protocol with Groth16 proofs and nullifier-based revocation."),

    p("blockchain","production-grade","🌉","Cross-Chain Bridge Protocol","Lock token on Chain A — mint wrapped token on Chain B with validator set. Users want to move assets between chains without centralized exchanges.",
      ["Solidity","Go","React","Hardhat"],"Hard","24-36 weeks",
      ["Token locking/unlocking","Cross-chain message passing","Multi-validator attestation","Replay protection","Emergency pause","Bridge fee distribution","Monitoring dashboard","Liquidity optimization"],
      "Lock-and-mint pattern. Off-chain validator coordination with multi-sig. On-chain fraud proofs. Time delays for large withdrawals.",
      "/contracts/source\n/contracts/dest\n/validators\n/api\n/frontend\n/infra",
      ["LayerZero / Axelar (reference)","Chainlink CCIP","ethers.js"],"PostgreSQL (bridge state), Redis (validator)","Ethereum + Polygon",
      "5-of-9 multi-sig validators. Time delays for large withdrawals. Emergency pause.","Add canonical token wrapping, liquidity pools, cross-chain swaps.",
      "Cross-chain messaging, validator sets, replay prevention, bridge security.","Show bridge dashboard with transfer history.","Design cross-chain bridge with lock-and-mint, validator attestation, and fraud proofs."),
    p("blockchain","production-grade","💱","On-Chain Derivatives Protocol","Perpetual futures DEX with up to 30x leverage, oracle pricing, and liquidations on Layer 2.",
      ["Solidity","Foundry","React","ethers.js","Chainlink"],"Hard","30-40 weeks",
      ["Perpetual futures trading","Up to 30x leverage","Oracle pricing","Liquidation engine","Order book (L2)","Margin system","Insurance fund","Realized/ unrealized P&L"],
      "Perpetual futures AMM with oracle-based pricing. Liquidation engine with partial liquidation. L2 order book for low latency.",
      "/contracts\n/frontend\n/oracle\n/liquidator\n/test",
      ["Chainlink Oracle","The Graph"],"Blockchain, The Graph, PostgreSQL (off-chain)","Layer 2 mainnet (after audit)",
      "Formal verification. Liquidation safeguards. Oracle manipulation resistance. Multi-sig admin.","Add cross-margining, portfolio margin, options trading.",
      "Perpetual futures, AMM design, oracle integration, liquidation engine.","Show trading interface with position management.","Design perpetual futures AMM with oracle pricing and liquidation engine."),
  ];

  global.TMProjects = { all: projects };
})(window);
